version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/code
hooks:
  BeforeInstall:
    - location: apache_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /home/ubuntu/code/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/code/apache_start.sh
      timeout: 300
      runas: root
