version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/
permissions:
   - object: test.py
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: /home/ubuntu/
      runas: root
    - location: /home/ubuntu/
      runas: root
   AfterInstall:
    - location: /home/ubuntu/test.py
      runas: root
